org.gradle.jvmargs=-Xmx3G
org.gradle.caching=true
org.gradle.parallel=true
org.gradle.configureondemand=true

org.gradle.configuration-cache=true
org.gradle.configuration-cache.parallel=true
org.gradle.configuration-cache.problems=warn

net.minecraftforge.gradle.merge-source-sets=true

minecraft_version=26.2
forge_version=65.0.0
neoforge_version=26.2.0.6-beta

mod_version=1.0.0
mod_group_id=com.autofarm
mod_id=autofarm
mod_name=AutoFarm
mod_license=MIT
mod_authors=Player
