modLoader="javafml"
loaderVersion="[61,)"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="${mod_authors}"
description='''
Auto-farming mod: automated fishing and mob attack.
'''

[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="[61,)"
    ordering="NONE"
    side="CLIENT"

[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="[${minecraft_version},)"
    ordering="NONE"
    side="CLIENT"
